
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = renesas-ra
board = uno_r4_minima
framework = arduino
lib_deps = RobTillaart/HX711

[env:01_sensor_test]
build_src_filter = +<01_sensor_test/*>

[env:02_structured_experiment]
build_src_filter = +<02_structured_experiment/*>